---
deployment:
  tasks:
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan config:clear
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan config:cache
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan route:clear
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan route:cache
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan view:clear
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan view:cache
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan migrate --force
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan db:seed --class=KategoriProdukSeeder --force
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan db:seed --class=TentangSeeder --force
    - /usr/local/bin/php /home/ldpcxuzg/akar-sehat/artisan db:seed --class=ProductArticleI18nSeeder --force
